server:
  port: 30001
spring:
  application:
    name: consumer
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
       defaultZone: http://127.0.0.1:10000/eureka,http://127.0.0.1:10001/eureka,http://127.0.0.1:10002/eureka
  instance:
    prefer-ip-address: true


